apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-thanos-app-test
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-helm:test  
spec:
  project: default
  source:
    path: helmapp/stages/test
    repoURL: https://github.com/pratik3686/kargo-demo-new
    targetRevision: main
  destination:
    namespace: kargo-demo-test
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2