apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'kargo'
spec:
  destination:
    name: 'in-cluster'
    namespace: 'kargo'
  source:
    chart: 'kargo'
    repoURL: 'ghcr.io/akuity/kargo-charts'
    targetRevision: 0.1.0
    helm:
      valuesObject:
        api:
          service:
            type: NodePort
            nodePort: 30084
          adminAccount:
            password: admin
            tokenSigningKey: ""
          argocd:
            urls:
              "": "https://localhost:8080"
  project: 'default'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true