apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30082
  target:
    kind: Service
    name: kargo-demo
images:
- name: 9673483686/some-nginx
  newName: 9673483686/some-nginx
  newTag: 0.0.2
- name: nginx
  newName: nginx
  newTag: 0.0.1
